##服务端口号
server:
  port: 80
###服务的别名---服务到注册中心的名称
spring:
  application:
    name: app-lhz-zuul
eureka:
  client:
    service-url:
      ##注册中心地址注册到地址
      defaultZone:  http://localhost:8100/eureka/
zuul:
  host:
    max-per-route-connections: 500
    socket-timeout-millis: 3000
    connect-timeout-millis: 3000

  routes:
    ##定义服务转发规则
    api-a:
      ###以api-member 开头的都会转发到会员服务
      path: /api-member/**
      ###zuul 默认整合ribbon 自动实现本地负载均衡
      serviceId: app-lhz-member
    api-b:
      path: /api-order/**
      serviceId: app-lhz-order
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 9000
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000

